language: go
dist: focal
go:
  - 1.15

addons: 
  apt: 
    update: true
    packages: 
      - ninja-build
      - npm 

install:
  - npm install webpack
  - npm i webpack-cli
  - npm i webpack-obfuscator
  - npm i javascript-obfuscator

script: 
  - go get -u ./build/cmd/bood/
  - cd example && bood
